// <auto-generated />
using System;
using HomeService.Infra.DataBase.SQLServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeService.Infra.DataBase.SQLServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240513185609_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpertService", b =>
                {
                    b.Property<int>("ExpertsId")
                        .HasColumnType("int");

                    b.Property<int>("ServicesId")
                        .HasColumnType("int");

                    b.HasKey("ExpertsId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("ExpertService");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpertId")
                        .HasColumnType("int");

                    b.Property<string>("FullAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpertId")
                        .IsUnique()
                        .HasFilter("[ExpertId] IS NOT NULL");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 248, DateTimeKind.Local).AddTicks(1985),
                            Email = "zahrasarmadi17@gmail.com",
                            FirstName = "زهرا",
                            Gender = 1,
                            IsDeleted = false,
                            LastName = "سرمدی",
                            Password = "zahrasarmadi",
                            PhoneNumber = "09927848276"
                        });
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6004),
                            Name = "آذربایجان شرقی"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6008),
                            Name = "آذربایجان غربی"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6010),
                            Name = "اردبیل"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6012),
                            Name = "اصفهان"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6014),
                            Name = "البرز"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6090),
                            Name = "ایلام"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6092),
                            Name = "بوشهر"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6095),
                            Name = "تهران"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6097),
                            Name = "چهارمحال و بختیاری"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6099),
                            Name = "خراسان جنوبی"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6102),
                            Name = "خراسان رضوی"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6104),
                            Name = "خراسان شمالی"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6106),
                            Name = "خوزستان"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6109),
                            Name = "زنجان"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6111),
                            Name = "سمنان"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6113),
                            Name = "سیستان و بلوچستان"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6116),
                            Name = "فارس"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6118),
                            Name = "قزوین"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6120),
                            Name = "قم"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6122),
                            Name = "کردستان"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6125),
                            Name = "کرمان"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6127),
                            Name = "کرمانشاه"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6130),
                            Name = "کهگیلویه و بویراحمد"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6132),
                            Name = "گلستان"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6134),
                            Name = "گیلان"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6136),
                            Name = "لرستان"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6138),
                            Name = "مازندران"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6140),
                            Name = "مرکزی"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6142),
                            Name = "هرمزگان"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6144),
                            Name = "همدان"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(6146),
                            Name = "یزد"
                        });
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAccept")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpertId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 250, DateTimeKind.Local).AddTicks(818),
                            CustomerId = 1,
                            Description = "کارش عالی بود",
                            ExpertId = 1,
                            IsAccept = false,
                            IsDeleted = false,
                            Score = 4,
                            Title = "عالی"
                        });
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackUpPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("BankCardNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackUpPhoneNumber = "09123669858",
                            BankCardNumber = "1234123412341234",
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 250, DateTimeKind.Local).AddTicks(5090),
                            FirstName = "سارا",
                            Gender = 1,
                            IsDeleted = false,
                            LastName = "محمودی",
                            PhoneNumber = "09192365988"
                        },
                        new
                        {
                            Id = 2,
                            BackUpPhoneNumber = "09123623258",
                            BankCardNumber = "1239684412341234",
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 250, DateTimeKind.Local).AddTicks(5096),
                            FirstName = "محمد",
                            Gender = 2,
                            IsDeleted = false,
                            LastName = "اصغری",
                            PhoneNumber = "09199655988"
                        });
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Expert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankCardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfrim")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Experts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankCardNumber = "1234123412341234",
                            BirthDate = new DateTime(1998, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(937),
                            FirstName = "منصور",
                            Gender = 2,
                            IsConfrim = true,
                            IsDeleted = false,
                            LastName = "آموزگار",
                            PhoneNumber = "09362356998"
                        });
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExpertId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(2614),
                            CustomerId = 1,
                            Description = "نظافت خونه صد متری هب طور کامل",
                            DoneAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(2619),
                            ExpertId = 1,
                            IsDeleted = false,
                            RequestedAt = new DateTime(2024, 5, 13, 22, 26, 8, 249, DateTimeKind.Local).AddTicks(2623),
                            ServiceId = 1,
                            Status = 6,
                            Title = "نظافت"
                        });
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ServiceSubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceSubCategoryId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(3870),
                            IsDeleted = false,
                            Name = "سرویس عادی نظافت",
                            Price = 700000,
                            ServiceSubCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(3874),
                            IsDeleted = false,
                            Name = "سرویس لوکسن نظافت",
                            Price = 850000,
                            ServiceSubCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(3876),
                            IsDeleted = false,
                            Name = "سرویس ویژه نظافت",
                            Price = 1000000,
                            ServiceSubCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(3879),
                            IsDeleted = false,
                            Name = "تعمیر و سرویس کولر آبی",
                            Price = 200000,
                            ServiceSubCategoryId = 4
                        });
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(6621),
                            IsDeleted = false,
                            Name = "تمیزکاری"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(6625),
                            IsDeleted = false,
                            Name = "ساختمان"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(6629),
                            IsDeleted = false,
                            Name = "تعمیرات اشیاء"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(6631),
                            IsDeleted = false,
                            Name = "اسباب کشی و حمل بار"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(6634),
                            IsDeleted = false,
                            Name = "خودرو"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(6637),
                            IsDeleted = false,
                            Name = "سازمان ها و مجتمع ها"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(6639),
                            IsDeleted = false,
                            Name = "سلامت و زیبایی"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(6642),
                            IsDeleted = false,
                            Name = "کشکول"
                        });
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.ServiceSubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("ServiceSubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8505),
                            IsDeleted = false,
                            Name = "نظافت و پذیرایی",
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8509),
                            IsDeleted = false,
                            Name = "شستشو",
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8512),
                            IsDeleted = false,
                            Name = "کارواش و دیتیلینگ",
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8514),
                            IsDeleted = false,
                            Name = "سرمایش و گرمایش",
                            ServiceCategoryId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8517),
                            IsDeleted = false,
                            Name = "نصب وتعمیر لوازم خانگی",
                            ServiceCategoryId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8520),
                            IsDeleted = false,
                            Name = "کارواش و دیتیلینگ",
                            ServiceCategoryId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8522),
                            IsDeleted = false,
                            Name = "خذمات کامپیوتری",
                            ServiceCategoryId = 3
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8525),
                            IsDeleted = false,
                            Name = "تعمیرات موبایل",
                            ServiceCategoryId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8527),
                            IsDeleted = false,
                            Name = "سرمایش و گرمایش",
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8530),
                            IsDeleted = false,
                            Name = "تعمیرا ساختمان",
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8532),
                            IsDeleted = false,
                            Name = "لوله کشی",
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8534),
                            IsDeleted = false,
                            Name = "طراحی و بازسازی ساختمان",
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8536),
                            IsDeleted = false,
                            Name = "برق کاری",
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8539),
                            IsDeleted = false,
                            Name = "چوب و کابینت",
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8541),
                            IsDeleted = false,
                            Name = "خدمات شیشه ای ساختمان",
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8544),
                            IsDeleted = false,
                            Name = "باغبانی و فضای سبز",
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8546),
                            IsDeleted = false,
                            Name = "باربری و جا به جایی",
                            ServiceCategoryId = 4
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8549),
                            IsDeleted = false,
                            Name = "خدمات و تعمیرات خودرو",
                            ServiceCategoryId = 5
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8551),
                            IsDeleted = false,
                            Name = "کارواش و دیتیلینگ",
                            ServiceCategoryId = 5
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8554),
                            IsDeleted = false,
                            Name = "خدمات شرکتی",
                            ServiceCategoryId = 6
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8557),
                            IsDeleted = false,
                            Name = "زیبایی بانوان",
                            ServiceCategoryId = 7
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8559),
                            IsDeleted = false,
                            Name = "پیرایش و زیبایی آقایان",
                            ServiceCategoryId = 7
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8562),
                            IsDeleted = false,
                            Name = "پزشکی و پرستاری",
                            ServiceCategoryId = 7
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 5, 13, 22, 26, 8, 251, DateTimeKind.Local).AddTicks(8564),
                            IsDeleted = false,
                            Name = "حیوانات خانگی",
                            ServiceCategoryId = 7
                        });
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("OrderId");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("ExpertService", b =>
                {
                    b.HasOne("HomeService.Domain.Core.Entities.Expert", null)
                        .WithMany()
                        .HasForeignKey("ExpertsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeService.Domain.Core.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Address", b =>
                {
                    b.HasOne("HomeService.Domain.Core.Entities.City", "City")
                        .WithMany("Address")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HomeService.Domain.Core.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HomeService.Domain.Core.Entities.Expert", "Expert")
                        .WithOne("Address")
                        .HasForeignKey("HomeService.Domain.Core.Entities.Address", "ExpertId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("City");

                    b.Navigation("Customer");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Comment", b =>
                {
                    b.HasOne("HomeService.Domain.Core.Entities.Customer", "Customer")
                        .WithMany("Comments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HomeService.Domain.Core.Entities.Expert", "Expert")
                        .WithMany("Comments")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Order", b =>
                {
                    b.HasOne("HomeService.Domain.Core.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HomeService.Domain.Core.Entities.Expert", "Expert")
                        .WithMany("Orders")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HomeService.Domain.Core.Entities.Service", "Service")
                        .WithMany("Orders")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Expert");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Service", b =>
                {
                    b.HasOne("HomeService.Domain.Core.Entities.ServiceSubCategory", "ServiceSubCategory")
                        .WithMany("Services")
                        .HasForeignKey("ServiceSubCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ServiceSubCategory");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.ServiceSubCategory", b =>
                {
                    b.HasOne("HomeService.Domain.Core.Entities.ServiceCategory", "ServiceCategory")
                        .WithMany("ServiceSubCategories")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Suggestion", b =>
                {
                    b.HasOne("HomeService.Domain.Core.Entities.Expert", "Expert")
                        .WithMany("Suggestions")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HomeService.Domain.Core.Entities.Order", "Order")
                        .WithMany("Suggestions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.City", b =>
                {
                    b.Navigation("Address");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Comments");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Expert", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Comments");

                    b.Navigation("Orders");

                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Order", b =>
                {
                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Service", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.ServiceCategory", b =>
                {
                    b.Navigation("ServiceSubCategories");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.ServiceSubCategory", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
