// <auto-generated />
using System;
using HomeService.Infra.DataBase.SQLServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeService.Infra.DataBase.SQLServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpertService", b =>
                {
                    b.Property<int>("ExpertsId")
                        .HasColumnType("int");

                    b.Property<int>("ServicesId")
                        .HasColumnType("int");

                    b.HasKey("ExpertsId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("ExpertService");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpertId")
                        .HasColumnType("int");

                    b.Property<string>("FullAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpertId")
                        .IsUnique()
                        .HasFilter("[ExpertId] IS NOT NULL");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 83, DateTimeKind.Local).AddTicks(6845),
                            Email = "zahrasarmadi17@gmail.com",
                            FirstName = "زهرا",
                            Gender = 1,
                            IsDeleted = false,
                            LastName = "سرمدی",
                            Password = "zahrasarmadi",
                            PhoneNumber = "09927848276"
                        });
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3532),
                            Name = "آذربایجان شرقی"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3535),
                            Name = "آذربایجان غربی"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3536),
                            Name = "اردبیل"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3538),
                            Name = "اصفهان"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3539),
                            Name = "البرز"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3541),
                            Name = "ایلام"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3543),
                            Name = "بوشهر"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3544),
                            Name = "تهران"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3545),
                            Name = "چهارمحال و بختیاری"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3547),
                            Name = "خراسان جنوبی"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3548),
                            Name = "خراسان رضوی"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3550),
                            Name = "خراسان شمالی"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3551),
                            Name = "خوزستان"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3553),
                            Name = "زنجان"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3554),
                            Name = "سمنان"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3555),
                            Name = "سیستان و بلوچستان"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3557),
                            Name = "فارس"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3558),
                            Name = "قزوین"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3560),
                            Name = "قم"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3561),
                            Name = "کردستان"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3563),
                            Name = "کرمان"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3564),
                            Name = "کرمانشاه"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3566),
                            Name = "کهگیلویه و بویراحمد"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3567),
                            Name = "گلستان"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3569),
                            Name = "گیلان"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3570),
                            Name = "لرستان"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3572),
                            Name = "مازندران"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3573),
                            Name = "مرکزی"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3575),
                            Name = "هرمزگان"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3576),
                            Name = "همدان"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 85, DateTimeKind.Local).AddTicks(3579),
                            Name = "یزد"
                        });
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpertId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackUpPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackUpPhoneNumber = "09123669858",
                            BankCardNumber = "1234123412341234",
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 86, DateTimeKind.Local).AddTicks(8754),
                            FirstName = "سارا",
                            Gender = 1,
                            IsDeleted = false,
                            LastName = "محمودی",
                            LastUpdatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 86, DateTimeKind.Local).AddTicks(8746),
                            PhoneNumber = "09192365988",
                            RegisteredAt = new DateTime(2024, 4, 30, 18, 0, 18, 86, DateTimeKind.Local).AddTicks(8754)
                        },
                        new
                        {
                            Id = 2,
                            BackUpPhoneNumber = "09123623258",
                            BankCardNumber = "1239684412341234",
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 86, DateTimeKind.Local).AddTicks(8759),
                            FirstName = "محمد",
                            Gender = 2,
                            IsDeleted = false,
                            LastName = "اصغری",
                            LastUpdatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 86, DateTimeKind.Local).AddTicks(8757),
                            PhoneNumber = "09199655988",
                            RegisteredAt = new DateTime(2024, 4, 30, 18, 0, 18, 86, DateTimeKind.Local).AddTicks(8759)
                        });
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Expert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfrim")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Experts");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExpertId")
                        .HasColumnType("int");

                    b.Property<string>("ImageAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceSubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId")
                        .IsUnique()
                        .HasFilter("[ExpertId] IS NOT NULL");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServiceCategoryId")
                        .IsUnique()
                        .HasFilter("[ServiceCategoryId] IS NOT NULL");

                    b.HasIndex("ServiceId")
                        .IsUnique()
                        .HasFilter("[ServiceId] IS NOT NULL");

                    b.HasIndex("ServiceSubCategoryId")
                        .IsUnique()
                        .HasFilter("[ServiceSubCategoryId] IS NOT NULL");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alt = "ساختمان",
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 87, DateTimeKind.Local).AddTicks(9031),
                            ImageAddress = "..\\HomeService\\HomeService.Endpoint.RazorPages.UI\\wwwroot\\img\\ServiceCategory\\f842e927-824f-49f6-8710-124e7f517ed6-mainCategory-icon.webp",
                            IsDeleted = false,
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Alt = "تعمیرات اشیاء",
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 87, DateTimeKind.Local).AddTicks(9034),
                            ImageAddress = "..\\HomeService\\HomeService.Endpoint.RazorPages.UI\\wwwroot\\img\\ServiceCategory\\08a5087d-cd08-49a2-82dd-4738cb2182bd-mainCategory-icon.webp",
                            IsDeleted = false,
                            ServiceCategoryId = 2
                        });
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExpertId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceSubCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceSubCategoryId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(1998),
                            IsDeleted = false,
                            Name = "سرویس عادی نظافت",
                            Price = 700000,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(2001),
                            IsDeleted = false,
                            Name = "سرویس لوکسن نظافت",
                            Price = 850000,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(2003),
                            IsDeleted = false,
                            Name = "سرویس ویژه نظافت",
                            Price = 1000000,
                            SubCategoryId = 1
                        });
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(4811),
                            IsDeleted = false,
                            Name = "تمیزکاری"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(4817),
                            IsDeleted = false,
                            Name = "ساختمان"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(4819),
                            IsDeleted = false,
                            Name = "تعمیرات اشیاء"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(4820),
                            IsDeleted = false,
                            Name = "اسباب کشی و حمل بار"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(4822),
                            IsDeleted = false,
                            Name = "خودرو"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(4824),
                            IsDeleted = false,
                            Name = "سازمان ها و مجتمع ها"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(4825),
                            IsDeleted = false,
                            Name = "سلامت و زیبایی"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(4827),
                            IsDeleted = false,
                            Name = "کشکول"
                        });
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.ServiceSubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("ServiceSubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6414),
                            IsDeleted = false,
                            Name = "نظافت و پذیرایی",
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6419),
                            IsDeleted = false,
                            Name = "شستشو",
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6422),
                            IsDeleted = false,
                            Name = "کارواش و دیتیلینگ",
                            ServiceCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6423),
                            IsDeleted = false,
                            Name = "سرمایش و گرمایش",
                            ServiceCategoryId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6425),
                            IsDeleted = false,
                            Name = "نصب وتعمیر لوازم خانگی",
                            ServiceCategoryId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6427),
                            IsDeleted = false,
                            Name = "کارواش و دیتیلینگ",
                            ServiceCategoryId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6429),
                            IsDeleted = false,
                            Name = "خذمات کامپیوتری",
                            ServiceCategoryId = 3
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6431),
                            IsDeleted = false,
                            Name = "تعمیرات موبایل",
                            ServiceCategoryId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6432),
                            IsDeleted = false,
                            Name = "سرمایش و گرمایش",
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6434),
                            IsDeleted = false,
                            Name = "تعمیرا ساختمان",
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6436),
                            IsDeleted = false,
                            Name = "لوله کشی",
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6437),
                            IsDeleted = false,
                            Name = "طراحی و بازسازی ساختمان",
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6439),
                            IsDeleted = false,
                            Name = "برق کاری",
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6441),
                            IsDeleted = false,
                            Name = "چوب و کابینت",
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6443),
                            IsDeleted = false,
                            Name = "خدمات شیشه ای ساختمان",
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6444),
                            IsDeleted = false,
                            Name = "باغبانی و فضای سبز",
                            ServiceCategoryId = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6446),
                            IsDeleted = false,
                            Name = "باربری و جا به جایی",
                            ServiceCategoryId = 4
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6448),
                            IsDeleted = false,
                            Name = "خدمات و تعمیرات خودرو",
                            ServiceCategoryId = 5
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6450),
                            IsDeleted = false,
                            Name = "کارواش و دیتیلینگ",
                            ServiceCategoryId = 5
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6452),
                            IsDeleted = false,
                            Name = "خدمات شرکتی",
                            ServiceCategoryId = 6
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6454),
                            IsDeleted = false,
                            Name = "زیبایی بانوان",
                            ServiceCategoryId = 7
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6455),
                            IsDeleted = false,
                            Name = "پیرایش و زیبایی آقایان",
                            ServiceCategoryId = 7
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6457),
                            IsDeleted = false,
                            Name = "پزشکی و پرستاری",
                            ServiceCategoryId = 7
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 4, 30, 18, 0, 18, 88, DateTimeKind.Local).AddTicks(6459),
                            IsDeleted = false,
                            Name = "حیوانات خانگی",
                            ServiceCategoryId = 7
                        });
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("OrderId");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("ExpertService", b =>
                {
                    b.HasOne("HomeService.Domain.Core.Entities.Expert", null)
                        .WithMany()
                        .HasForeignKey("ExpertsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeService.Domain.Core.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Address", b =>
                {
                    b.HasOne("HomeService.Domain.Core.Entities.City", "City")
                        .WithMany("Address")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HomeService.Domain.Core.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HomeService.Domain.Core.Entities.Expert", "Expert")
                        .WithOne("Address")
                        .HasForeignKey("HomeService.Domain.Core.Entities.Address", "ExpertId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("City");

                    b.Navigation("Customer");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Comment", b =>
                {
                    b.HasOne("HomeService.Domain.Core.Entities.Customer", "Customer")
                        .WithMany("Comments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HomeService.Domain.Core.Entities.Expert", "Expert")
                        .WithMany("Comments")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Image", b =>
                {
                    b.HasOne("HomeService.Domain.Core.Entities.Expert", "Expert")
                        .WithOne("ProfileImage")
                        .HasForeignKey("HomeService.Domain.Core.Entities.Image", "ExpertId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HomeService.Domain.Core.Entities.Order", "Order")
                        .WithMany("Images")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HomeService.Domain.Core.Entities.ServiceCategory", "ServiceCategory")
                        .WithOne("Image")
                        .HasForeignKey("HomeService.Domain.Core.Entities.Image", "ServiceCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HomeService.Domain.Core.Entities.Service", "Service")
                        .WithOne("Image")
                        .HasForeignKey("HomeService.Domain.Core.Entities.Image", "ServiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HomeService.Domain.Core.Entities.ServiceSubCategory", "ServiceSubCategory")
                        .WithOne("Image")
                        .HasForeignKey("HomeService.Domain.Core.Entities.Image", "ServiceSubCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Expert");

                    b.Navigation("Order");

                    b.Navigation("Service");

                    b.Navigation("ServiceCategory");

                    b.Navigation("ServiceSubCategory");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Order", b =>
                {
                    b.HasOne("HomeService.Domain.Core.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HomeService.Domain.Core.Entities.Expert", "Expert")
                        .WithMany("Orders")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HomeService.Domain.Core.Entities.Service", "Service")
                        .WithMany("Orders")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Expert");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Service", b =>
                {
                    b.HasOne("HomeService.Domain.Core.Entities.ServiceSubCategory", "ServiceSubCategory")
                        .WithMany("Services")
                        .HasForeignKey("ServiceSubCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ServiceSubCategory");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.ServiceSubCategory", b =>
                {
                    b.HasOne("HomeService.Domain.Core.Entities.ServiceCategory", "ServiceCategory")
                        .WithMany("ServiceSubCategories")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Suggestion", b =>
                {
                    b.HasOne("HomeService.Domain.Core.Entities.Expert", "Expert")
                        .WithMany("Suggestions")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HomeService.Domain.Core.Entities.Order", "Order")
                        .WithMany("Suggestions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.City", b =>
                {
                    b.Navigation("Address");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Comments");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Expert", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Comments");

                    b.Navigation("Orders");

                    b.Navigation("ProfileImage")
                        .IsRequired();

                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Order", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.Service", b =>
                {
                    b.Navigation("Image");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Image");

                    b.Navigation("ServiceSubCategories");
                });

            modelBuilder.Entity("HomeService.Domain.Core.Entities.ServiceSubCategory", b =>
                {
                    b.Navigation("Image");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
