using HomeService.Domain.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace HomeService.Infra.DataBase.SQLServer.Configuration;

public class ServiceConfiguration : IEntityTypeConfiguration<Service>
{
    public void Configure(EntityTypeBuilder<Service> builder)
    {
        builder.HasOne(s => s.ServiceSubCategory)
            .WithMany(s => s.Services)
            .OnDelete(DeleteBehavior.NoAction);

        builder.HasMany(s => s.Experts)
            .WithMany(e => e.Services);

        builder.HasMany(s => s.Orders)
            .WithOne(o => o.Service)
            .OnDelete(DeleteBehavior.NoAction);

        builder.HasData
            (
            new Service { Id = 1, Name = "سرویس عادی نظافت", Price = 700000, ServiceSubCategoryId = 1, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 2, Name = "سرویس لوکس نظافت", Price = 850000, ServiceSubCategoryId = 1, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 3, Name = "سرویس ویژه نظافت", Price = 1000000, ServiceSubCategoryId = 1, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 5, Name = "نظافت راه‌پله", Price = 1000000, ServiceSubCategoryId = 1, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 6, Name = "سرویس نظافت فوری", Price = 1000000, ServiceSubCategoryId = 1, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 7, Name = "پذیرایی", Price = 1000000, ServiceSubCategoryId = 1, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 8, Name = "کارگر ساده", Price = 1000000, ServiceSubCategoryId = 1, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 9, Name = "سمپاشی فضای داخلی", Price = 1000000, ServiceSubCategoryId = 1, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 10, Name = "ضدعفونی منزل و محل کار", Price = 1000000, ServiceSubCategoryId = 1, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 11, Name = "شستشوی مبل ،فرش و موکت در محل", Price = 1000000, ServiceSubCategoryId = 2, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 262, Name = "قالیشویی", Price = 1000000, ServiceSubCategoryId = 2, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 12, Name = "خشکشویی", Price = 1000000, ServiceSubCategoryId = 2, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 13, Name = "پرده شویی", Price = 1000000, ServiceSubCategoryId = 2, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 25, Name = "تعمیر و سرویس کولر آبی", Price = 1000000, ServiceSubCategoryId = 9, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 26, Name = "تعمیر کولر گازی و داکت اسپلیت", Price = 1000000, ServiceSubCategoryId = 9, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 27, Name = "تعمیر و سرویس پکیج", Price = 1000000, ServiceSubCategoryId = 9, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 28, Name = "تعمیر و سرویس ابگرمکن", Price = 1000000, ServiceSubCategoryId = 9, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 29, Name = "کانال سازی کولر", Price = 1000000, ServiceSubCategoryId = 9, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 32, Name = "سرویس و تعمیر چیلر", Price = 1000000, ServiceSubCategoryId = 9, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 33, Name = "تعمیر و سرویس فن کویل", Price = 1000000, ServiceSubCategoryId = 9, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 34, Name = "نصب و تعمیر بخاری گازی و شومینه", Price = 1000000, ServiceSubCategoryId = 9, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 36, Name = "بهبود آلاینده‌های موتورخانه با دستگاه آنالیز", Price = 1000000, ServiceSubCategoryId = 9, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 37, Name = "ساخت و نصب توری", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 38, Name = "جوشکاری و آهنگری ، درب و پنجره آهنی", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 39, Name = "دوخت و نصب پرده", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 40, Name = "کاشی کاری و سرامیک", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 41, Name = "بنایی", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 42, Name = "کلید سازی", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 43, Name = "نصب و تعمیر انواع کفپوش و دیوارپوش", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 44, Name = "کچ کاری و رابیتس کاری", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 45, Name = "آچار فرانسه", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 46, Name = "دریل کاری", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 47, Name = "نصب ایزوگام ، قیرگونی و آسفالت", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 48, Name = "تعمیرات نما و نماشویی", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 49, Name = "کفسابی", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 50, Name = "تخریب", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 51, Name = "سقف و دیوار PVC و اسمان مجازی", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 52, Name = "شیروانی و ایرانیت", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 53, Name = "تعمیر و نگهداری استخر", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 54, Name = "کپسول آتش‌ نشانی", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 55, Name = "کناف کاری", Price = 1000000, ServiceSubCategoryId = 10, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 56, Name = "نصب و تعمیر شیرآلات", Price = 1000000, ServiceSubCategoryId = 11, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 57, Name = "تخلیه چاه و لوله بازکنی", Price = 1000000, ServiceSubCategoryId = 11, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 58, Name = "لوله کشی آب و فاضلاب", Price = 1000000, ServiceSubCategoryId = 11, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 59, Name = "نصب و سرویس توالت فرنگی و ایرانی", Price = 1000000, ServiceSubCategoryId = 11, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 60, Name = "تشخیص و ترمیم ترکیدگی لوله", Price = 1000000, ServiceSubCategoryId = 11, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 61, Name = "پمپ و منبع آب", Price = 1000000, ServiceSubCategoryId = 11, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 62, Name = "نصب و تعمیر دستگاه تصفیه آب", Price = 1000000, ServiceSubCategoryId = 11, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 63, Name = "نصب و تعمیر فلاش تانک و سیفون", Price = 1000000, ServiceSubCategoryId = 11, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 64, Name = "لوله کشی گاز", Price = 1000000, ServiceSubCategoryId = 11, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 65, Name = "نصب سینک ظرفشویی", Price = 1000000, ServiceSubCategoryId = 11, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 66, Name = "نصب روشویی", Price = 1000000, ServiceSubCategoryId = 11, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 67, Name = "نصب و تعمیر وال هنگ", Price = 1000000, ServiceSubCategoryId = 11, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 68, Name = "اتصال به شبکه فاضلاب شهری", Price = 1000000, ServiceSubCategoryId = 11, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 69, Name = "مشاوره و بازسازی ساختمان", Price = 1000000, ServiceSubCategoryId = 12, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 70, Name = "دکوراسیون و طراحی ساختمان", Price = 1000000, ServiceSubCategoryId = 12, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 71, Name = "رفع اتصالی", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 72, Name = "نصب و تعمیر آیفون صوتی و تصویری", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 73, Name = "نصب لوستر و چراغ", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 74, Name = "سیم کشی تلفن و نصب سانترال", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 75, Name = "نصب و تعمیر آنتن تلویزیون", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 76, Name = "نصب و تعمیر دوربین مداربسته", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 77, Name = "کلید و پریز", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 78, Name = "تعمیر و سرویس آسانسور", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 79, Name = "نصب و تعمیر کرکره برقی", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 80, Name = "نصب و تعمیر جک پارکینگ و آرام بند", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 81, Name = "هواکش و تهویه مطبوع", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 82, Name = "ساخت و تعمیر تابلو روان و چلنیوم", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 83, Name = "نصب و تعمیر بالابر", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 84, Name = "نصب و تعمیر دزدگیر اماکن", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 85, Name = "سیم پیجی", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 86, Name = "خدمات برق صنعتی و سه فاز", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 87, Name = "نصب سنسور و تایمر", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 88, Name = "نصب محافظ برق و استابلایزر", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 89, Name = "ساهت و تعمیر تابلو برق", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 90, Name = "طراحی و اجرای نور مخفی", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 91, Name = "نصب داکت و ترانکینگ", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 92, Name = "نصب و تعمیر زنراتور و برق اضطراری", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 93, Name = "نصب و تعمیر اگزاست‌فن و سانتریفیوژ", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 94, Name = "طراحی و علامت گذاری جعبه فیوز", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 95, Name = "سیستم اعلام و اطفاء جریق", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 96, Name = "سیم کشی ارت", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 97, Name = "هوشمندسازی ساختمان", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 98, Name = "طراحی و اجرای فنس الکتریکی", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 99, Name = "نصب و تعمیر راه بند", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 100, Name = "نصب و سرویس پله برقی", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 101, Name = "ساخت ، نصب و تعمیر کابینت", Price = 1000000, ServiceSubCategoryId = 14, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 102, Name = "نجاری", Price = 1000000, ServiceSubCategoryId = 14, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 103, Name = "تعمیرا مبلمان", Price = 1000000, ServiceSubCategoryId = 14, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 104, Name = "خدمات درب چوبی و ضدسرقت", Price = 1000000, ServiceSubCategoryId = 14, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 105, Name = "تعمیر و ساخت کمد دیواری", Price = 1000000, ServiceSubCategoryId = 14, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 106, Name = "شیشه بری و آینه کاری", Price = 1000000, ServiceSubCategoryId = 14, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 107, Name = "ساخت ، رگلاژ درب و پنجره آلمینیومی و UPVC", Price = 1000000, ServiceSubCategoryId = 15, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 108, Name = "شیشه ریلی و جام بالکن", Price = 1000000, ServiceSubCategoryId = 15, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 109, Name = "نصب و تعمیر درب اتوماتیک", Price = 1000000, ServiceSubCategoryId = 15, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 110, Name = "شیشه ریلی اسلاید", Price = 1000000, ServiceSubCategoryId = 15, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 111, Name = "ساخت کابین دوش", Price = 1000000, ServiceSubCategoryId = 15, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 112, Name = "باغبانی", Price = 1000000, ServiceSubCategoryId = 16, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 113, Name = "نگهداری از گیاهان آپارتمانی", Price = 1000000, ServiceSubCategoryId = 16, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 114, Name = "سمپاچی باغچه و فضای سبز", Price = 1000000, ServiceSubCategoryId = 16, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 115, Name = "مشاوره گل و گیاه", Price = 1000000, ServiceSubCategoryId = 16, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 116, Name = "طراحی و اجرای فضای سبز", Price = 1000000, ServiceSubCategoryId = 16, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 117, Name = "روف گاردن", Price = 1000000, ServiceSubCategoryId = 16, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 118, Name = "هرس درختان", Price = 1000000, ServiceSubCategoryId = 16, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 120, Name = "تعمیر کولر گازی و اسپلیت", Price = 1000000, ServiceSubCategoryId = 4, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 122, Name = "تعمیر و سرویس آبگرمکن", Price = 1000000, ServiceSubCategoryId = 4, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 124, Name = "نصب و تعمیر رادیاتور شوفاژ", Price = 1000000, ServiceSubCategoryId = 4, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 125, Name = "تعمیر و نگهداری موتورخانه", Price = 1000000, ServiceSubCategoryId = 4, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 127, Name = "نصب و سرویس فن کویل", Price = 1000000, ServiceSubCategoryId = 4, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 128, Name = "نصب و تعمیر بخاری و شومینه", Price = 1000000, ServiceSubCategoryId = 4, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 129, Name = "نصب و تعمیر VRF و DVR", Price = 1000000, ServiceSubCategoryId = 4, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 130, Name = "بهبود الاینده‌های موتورخانه با دستگاه آنالیز", Price = 1000000, ServiceSubCategoryId = 4, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 131, Name = "نصب و تعمیر یخچال و فریزر", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 132, Name = "نصب و تعمیر ماشین لباسشویی", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 133, Name = "نصب و تعمیر اجاق گاز", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 134, Name = "نصب و تعمیر ماشین ظرفشویی", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 135, Name = "تعمیرات تخصصی تلویزیون", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 136, Name = "نصب تلویزیون و لوازم صوتی تصویری", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 137, Name = "نصب و تعمیر مایکروویو و سولاردام", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 138, Name = "نصب و تعمیر هود آشپزخانه", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 139, Name = "نصب و تعمیر جاروبرقی", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 140, Name = "نصب و تعمیر چرخ خیاطی", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 141, Name = "نصب و تعمیر تردمیل", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 142, Name = "تعمیر چایی ساز و قهوه ساز", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 143, Name = "تعمیر دستگاه بخور", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 144, Name = "تعمیر پنکه", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 145, Name = "نصب و تعمیر فر", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 146, Name = "تعمیر اتو", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 147, Name = "تعمیر آبمیوه گیری و مخلوط کن", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 148, Name = "تعمیر ساندبار و اسپیکر", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 149, Name = "تعمیر کنسول بازی", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 150, Name = "تعمیر بخارشور", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 151, Name = "تعمیر غذاساز و خردکن", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 152, Name = "تعمیرات ریش تراش و اپلیدی", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 153, Name = "تعمیر سینمای خانگی", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 154, Name = "تعمیر چرخ گوشت", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 155, Name = "تعمیر رادیو و ضبط صوت", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 156, Name = "تعمیر صندلی ماساژور", Price = 1000000, ServiceSubCategoryId = 13, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 157, Name = "تعمیر سرخ کن", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 158, Name = "تعمیر بخارپز و پلوپز", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 159, Name = "تعمیر سشوار", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 160, Name = "تعمیر شوفاژ برقی", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 161, Name = "ترمیم و بازسازی ظروف آشپزخانه", Price = 1000000, ServiceSubCategoryId = 5, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 162, Name = "تعمیر کامپیوتر و لپ تاپ", Price = 1000000, ServiceSubCategoryId = 7, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 163, Name = "تعمیر ماشین‌های اداری", Price = 1000000, ServiceSubCategoryId = 7, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 164, Name = "پشتیبانی شبکه و سرور", Price = 1000000, ServiceSubCategoryId = 7, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 165, Name = "مودم و اینترنت", Price = 1000000, ServiceSubCategoryId = 7, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 166, Name = "طراحی سایت و لوگو", Price = 1000000, ServiceSubCategoryId = 7, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 167, Name = "نصب و راه‌اندازی VoIP", Price = 1000000, ServiceSubCategoryId = 7, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 168, Name = "تعمیر دستگاه کارتخوان و بارکدخوان", Price = 1000000, ServiceSubCategoryId = 7, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 169, Name = "خدمات تاچ و ال سی دی", Price = 1000000, ServiceSubCategoryId = 8, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 170, Name = "خدمات باتری", Price = 1000000, ServiceSubCategoryId = 8, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 171, Name = "خدمات عیب‌یابی و تعمیر برد", Price = 1000000, ServiceSubCategoryId = 8, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 172, Name = "خدمات نرم افزاری", Price = 1000000, ServiceSubCategoryId = 8, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 173, Name = "مشاوره خرید موبایل و کالاهای دیجیتال", Price = 1000000, ServiceSubCategoryId = 8, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 174, Name = "خدمات اسپیکر", Price = 1000000, ServiceSubCategoryId = 8, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 175, Name = "خدمات فریم و قاب", Price = 1000000, ServiceSubCategoryId = 8, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 176, Name = "خدمات دوربین", Price = 1000000, ServiceSubCategoryId = 8, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 177, Name = "خدمات سنسور", Price = 1000000, ServiceSubCategoryId = 8, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 178, Name = "اسباب کشی با خاور و کامیون", Price = 1000000, ServiceSubCategoryId = 17, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 179, Name = "اسباب کشی و حمل بار بین شهری", Price = 1000000, ServiceSubCategoryId = 17, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 180, Name = "اسباب کشی با وانت و نیسان", Price = 1000000, ServiceSubCategoryId = 17, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 181, Name = "سرویس بسته بندی", Price = 1000000, ServiceSubCategoryId = 17, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 182, Name = "کارگر جا به جایی", Price = 1000000, ServiceSubCategoryId = 17, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 183, Name = "جا به جایی گاو صندوق", Price = 1000000, ServiceSubCategoryId = 17, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 184, Name = "حمل نخاله و ضایعات ساختمانی", Price = 1000000, ServiceSubCategoryId = 17, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 185, Name = "اسباب کشی شرکت ها و سازمان ها", Price = 1000000, ServiceSubCategoryId = 17, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 186, Name = "خرید ملزومات بسته بندی", Price = 1000000, ServiceSubCategoryId = 17, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 187, Name = "شارژ گاز کولر ماشین", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 188, Name = "تعویض باتری خودرو", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 189, Name = "امداد خودرو", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 190, Name = "برق و باتری خودرو", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 191, Name = "مکانیگی خودرو", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 192, Name = "تست دیاگ و ریمپ ECU خودرو", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 193, Name = "حمل خودرو", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 194, Name = "تعویض روغن خودرو", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 195, Name = "پنچرگیری و تعویض لاستیک", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 196, Name = "کارشناسی خودرو", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 197, Name = "تعویض لنت خودرو", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 198, Name = "تعویض شمع و وایر خودرو", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 199, Name = "کاهش مصرف سوخت", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 200, Name = "سرویس دوره ای گیربکس اتوماتیک", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 201, Name = "نصب GPS خودرو", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 202, Name = "نصب دزدگیر خودرو", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 203, Name = "سپرسازی و جوش پلاستیک", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 204, Name = "تعویض شیشه خودرو", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 205, Name = "تعمیر موتورسیکلت", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 206, Name = "سوخت رسانی", Price = 1000000,ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 207, Name = "ساخت سوئیچ و ریموت خودرو در محل", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 208, Name = "تعمیر و تعویض چراغ خودرو", Price = 1000000, ServiceSubCategoryId = 18, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 209, Name = "سرامیک خودرو", Price = 1000000, ServiceSubCategoryId = 19, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 210, Name = "کارواش نانو", Price = 1000000, ServiceSubCategoryId = 19, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 211, Name = "کارواش با آب", Price = 1000000, ServiceSubCategoryId = 19, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 212, Name = "واکس و پولیش خودرو", Price = 1000000, ServiceSubCategoryId = 19, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 213, Name = "صفرشویی خودرو", Price = 1000000, ServiceSubCategoryId = 19, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 214, Name = "موتورشویی خودرو", Price = 1000000, ServiceSubCategoryId = 19, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 215, Name = "پکیج کارواش VIP", Price = 1000000, ServiceSubCategoryId = 19, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 216, Name = "شفاف سازی چراغ خودرو", Price = 1000000, ServiceSubCategoryId = 19, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 217, Name = "احیای رنگ خودرو", Price = 1000000, ServiceSubCategoryId = 19, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 218, Name = "صافکاری و نقاشی خودرو", Price = 1000000, ServiceSubCategoryId = 19, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 219, Name = "نصب شیشه دودی خودرو در محل", Price = 1000000, ServiceSubCategoryId = 19, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 220, Name = "خدمات شرکتی ویژه شرکت ها کوچک و متوسط", Price = 1000000, ServiceSubCategoryId = 20, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 221, Name = "خدمات شرکتی ویژه سازمان های بزرگ", Price = 1000000, ServiceSubCategoryId = 20, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 222, Name = "خدمات ناخن", Price = 1000000, ServiceSubCategoryId = 21, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 223, Name = "خدمات ویژه ناخن", Price = 1000000, ServiceSubCategoryId = 21, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 224, Name = "اصلاح صورت و ابرو بانوان", Price = 1000000, ServiceSubCategoryId = 21, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 225, Name = "اپیلاسیون بانوان در خانه", Price = 1000000, ServiceSubCategoryId = 21, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 226, Name = "براشینگ مو بانوان", Price = 1000000, ServiceSubCategoryId = 21, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 227, Name = "رنگ مو بانوان", Price = 1000000, ServiceSubCategoryId = 21, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 228, Name = "مش ، لایت ، بالیاژ و آمبره بانوان", Price = 1000000, ServiceSubCategoryId = 21, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 229, Name = "لیفت و لمینت مژه و ابرو بانوان", Price = 1000000, ServiceSubCategoryId = 21, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 230, Name = "کاشت و اکستنشن مژه بانوان در خانه", Price = 1000000, ServiceSubCategoryId = 21, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 261, Name = "کراتینه و ویتامینه مو بانوان", Price = 1000000, ServiceSubCategoryId = 21, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 231, Name = "پاکسازی و لایه برداری پوست بانوان", Price = 1000000, ServiceSubCategoryId = 21, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 232, Name = "شینیون مو بانوان در خانه", Price = 1000000, ServiceSubCategoryId = 21, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 233, Name = "آرایش صورت بانوان در خانه", Price = 1000000, ServiceSubCategoryId = 21, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 234, Name = "بافت مو بانوان در خانه", Price = 1000000, ServiceSubCategoryId = 21, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 235, Name = "اکستنشن مو بانوان در خانه", Price = 1000000, ServiceSubCategoryId = 21, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 236, Name = "میکروپیمنتیشن و میکروبلیدینگ بانوان", Price = 1000000, ServiceSubCategoryId = 21, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 237, Name = "کوتاهی مو بانوان", Price = 1000000, ServiceSubCategoryId = 21, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 238, Name = "درمان سرپایی در محل", Price = 1000000, ServiceSubCategoryId = 23, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 239, Name = "تزریقات در منزل", Price = 1000000, ServiceSubCategoryId = 23, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 240, Name = "پرستاری و مراقبت بیمار", Price = 1000000, ServiceSubCategoryId = 23, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 241, Name = "پرستاری و مراقبت سالمند", Price = 1000000, ServiceSubCategoryId = 23, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 242, Name = "آزمایش و نمونه گیری در منزل", Price = 1000000, ServiceSubCategoryId = 23, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 243, Name = "ICU در منزل", Price = 1000000, ServiceSubCategoryId = 23, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 244, Name = "معاینه پزشکی", Price = 1000000, ServiceSubCategoryId = 23, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 245, Name = "فیزیوتراپی در منزل", Price = 1000000, ServiceSubCategoryId = 23, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 246, Name = "اصلاح سر و صورت آقایان", Price = 1000000, ServiceSubCategoryId = 22, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 247, Name = "سرویس ماهانه پیرایش اقایان", Price = 1000000, ServiceSubCategoryId = 22, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 248, Name = "خدمات ناخن آقایان", Price = 1000000, ServiceSubCategoryId = 22, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 249, Name = "مراقبت و زیبایی اقایان", Price = 1000000, ServiceSubCategoryId = 22, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 250, Name = "گریم داماد", Price = 1000000, ServiceSubCategoryId = 22, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 251, Name = "هتل های حیوانات خانگی", Price = 1000000, ServiceSubCategoryId = 24, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 252, Name = "خدمات دامپزشکی در محل", Price = 1000000, ServiceSubCategoryId = 24, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 253, Name = "خدمات تربیتی حیوانات خانگی", Price = 1000000, ServiceSubCategoryId = 24, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 254, Name = "خدمات شستشو و آرایش حیوانات خانگی", Price = 1000000, ServiceSubCategoryId = 24, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 255, Name = "پت شاپ", Price = 1000000, ServiceSubCategoryId = 24, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 256, Name = "کلاس سی ایکس در خانه", Price = 1000000, ServiceSubCategoryId = 25, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 257, Name = "برنامه ورزشی و تغذیه", Price = 1000000, ServiceSubCategoryId = 25, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 258, Name = "کلاس یوگا در خانه", Price = 1000000, ServiceSubCategoryId = 25, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 259, Name = "کلاس پیلاتس در خانه", Price = 1000000, ServiceSubCategoryId = 25, CreatedAt = DateTime.Now, IsDeleted = false },
            new Service { Id = 260, Name = "حرکات اصلاحی", Price = 1000000, ServiceSubCategoryId = 25, CreatedAt = DateTime.Now, IsDeleted = false }
            );
    }
}